#!/usr/bin/env bash

###############################################################################
# EFDN / App bootstrap script (Windows Git Bash / Linux / macOS)
#
# Env precedence (later wins):
#   1) .env.init     (bootstrap defaults)
#   2) .env          (generated by database_setup; or committed for dev)
#   3) .env.local    (developer overrides / machine-specific)
#
# We explicitly 'export' all envs so subprocesses (python/uvicorn) inherit them.
###############################################################################

set -e  # stop on first error

########################################
# CONFIGURATION YOU CAN ADJUST
########################################
VENV_DIR=".venv"
BACKEND_APP_MODULE_DEFAULT="app:app"
UVICORN_HOST="0.0.0.0"
UVICORN_PORT="8000"
MIGRATIONS_DIR="migrations"

########################################
# helper: pretty log line
########################################
log () { echo -e "\n==== $1 ====\n"; }

########################################
# detect platform / python command
########################################
IS_WINDOWS=0
case "$OSTYPE" in
  msys*|cygwin*|win32*) IS_WINDOWS=1 ;;
esac

if [ "$IS_WINDOWS" -eq 1 ]; then
    if command -v python >/dev/null 2>&1; then
        PYTHON_CMD="python"
    else
        echo "ERROR: Could not find 'python' on PATH in Git Bash."; exit 1
    fi
    ACTIVATE_PATH="$VENV_DIR/Scripts/activate"
else
    if command -v python3 >/dev/null 2>&1; then
        PYTHON_CMD="python3"
    elif command -v python >/dev/null 2>&1; then
        PYTHON_CMD="python"
    else
        echo "ERROR: Could not find python3 or python on PATH."; exit 1
    fi
    ACTIVATE_PATH="$VENV_DIR/bin/activate"
fi

log "Using python command: $PYTHON_CMD"
log "Will activate venv from: $ACTIVATE_PATH"

########################################
# utilities: env loading / masking
########################################
# Safely load KEY=VALUE pairs from a .env-style file:
# - strips CRLF
# - ignores comments & blank lines
# - exports variables to the current shell
load_env_file () {
    local file="$1"
    if [ -f "$file" ]; then
        log "Loading env from $file"
        set -a
        # shellcheck disable=SC1090
        source /dev/stdin <<EOF
$(sed -e 's/\r$//' "$file" | grep -E '^[[:space:]]*[^#[:space:]]' || true)
EOF
        set +a
    else
        echo "(skip) $file not found"
    fi
}

mask_val () {
    # mask long values for display; leave short ones alone
    local v="$1"
    local n=${#v}
    if [ "$n" -le 6 ]; then echo "$v"; else echo "${v:0:3}***${v: -2}"; fi
}

preview_env () {
    echo "APP_NAME=$(mask_val "${APP_NAME:-}")"
    echo "PG_DB_NAME=$(mask_val "${PG_DB_NAME:-}")"
    echo "PG_DB_USER=$(mask_val "${PG_DB_USER:-}")"
    echo "PG_DB_HOST=$(mask_val "${PG_DB_HOST:-}")"
    echo "PG_DB_PORT=$(mask_val "${PG_DB_PORT:-}")"
}

########################################
# 0) Ensure .env.init exists (bootstrap source of truth)
########################################
if [ ! -f ".env.init" ]; then
    echo ""
    echo "ERROR: .env.init not found in project root."
    echo "Please create it first with required bootstrap keys."
    exit 1
fi

########################################
# 1) Load envs with clear precedence
#    You can flip the order if you prefer .env.init to win over others.
########################################
# Start with .env.init (baseline)
load_env_file ".env.init"
# Then .env (committed/generated)
[ -f ".env" ] && load_env_file ".env"
# Finally .env.local (personal overrides)
[ -f ".env.local" ] && load_env_file ".env.local"

########################################
# 2) Validate required bootstrap keys from .env.init
########################################
REQUIRED_BOOTSTRAP=(
  "APP_NAME"
  "SECRET_KEY"
  "PG_INIT_DB_NAME"
  "PG_INIT_DB_USER"
  "PG_INIT_DB_PASSWORD"
  "PG_INIT_DB_HOST"
  "PG_INIT_DB_PORT"
)

MISSING_ANY=0
for VAR in "${REQUIRED_BOOTSTRAP[@]}"; do
    if [ -z "${!VAR}" ]; then
        echo "ERROR: $VAR is missing or empty (needed for bootstrap)"
        MISSING_ANY=1
    fi
done

if [ "$MISSING_ANY" -ne 0 ]; then
    echo ""
    echo "One or more required bootstrap variables are not set."
    echo "Fix .env.init (or your .env/.env.local overrides) and re-run."
    exit 1
fi

########################################
# 3) Check migrations directory exists
########################################
if [ ! -d "$MIGRATIONS_DIR" ]; then
    echo ""
    echo "ERROR: migrations directory '$MIGRATIONS_DIR' not found."
    echo "Create it (with .sql files) or update MIGRATIONS_DIR."
    exit 1
fi

########################################
# 4) Create / Activate venv
########################################
if [ ! -d "$VENV_DIR" ]; then
    log "Creating virtual environment in $VENV_DIR"
    "$PYTHON_CMD" -m venv "$VENV_DIR"
fi

if [ ! -f "$ACTIVATE_PATH" ]; then
    echo "ERROR: Can't find venv activate script at $ACTIVATE_PATH"
    exit 1
fi

log "Activating virtual environment"
# shellcheck disable=SC1090
source "$ACTIVATE_PATH"
export PYTHONUNBUFFERED=1

########################################
# 5) Install requirements + core deps
########################################
if [ -f "requirements.txt" ]; then
    log "Installing requirements.txt"
    pip install -r requirements.txt
else
    log "requirements.txt not found, continuing without it"
fi

log "Ensuring core bootstrap deps (psycopg2-binary, python-dotenv, uvicorn, fastapi)"
pip install psycopg2-binary python-dotenv uvicorn fastapi

########################################
# 6) Run DB bootstrap & migrations
#    - uses PG_INIT_DB_* (exported above)
#    - typically generates/updates .env with runtime PG_DB_* creds
########################################
log "Running database bootstrap & migrations"
"$PYTHON_CMD" -m database_setup --migrations-dir "$MIGRATIONS_DIR"

########################################
# 7) Re-load runtime envs *after* bootstrap
#    So uvicorn/app reads the fresh PG_DB_* values from generated .env
########################################
if [ -f ".env" ]; then
    load_env_file ".env"
fi
if [ -f ".env.local" ]; then
    load_env_file ".env.local"
fi

# Sanity: show the key DB envs we're about to run with (masked)
log "Runtime env preview (masked)"
preview_env

# Soft-validate known runtime keys (adjust to your app’s needs)
RUNTIME_KEYS=( "PG_DB_NAME" "PG_DB_USER" "PG_DB_PASSWORD" "PG_DB_HOST" "PG_DB_PORT" )
MISS=0
for VAR in "${RUNTIME_KEYS[@]}"; do
  if [ -z "${!VAR}" ]; then
    echo "WARN: $VAR appears empty after bootstrap. If this is unexpected, check database_setup output and .env content."
    MISS=1
  fi
done
[ "$MISS" -ne 0 ] && echo "Continuing anyway…"

########################################
# 8) Launch FastAPI backend with uvicorn
########################################
export WATCHFILES_FORCE_POLLING=1

# Allow BACKEND_APP_MODULE override from env; fall back to default
BACKEND_APP_MODULE="${BACKEND_APP_MODULE:-$BACKEND_APP_MODULE_DEFAULT}"

log "Starting FastAPI with uvicorn ($BACKEND_APP_MODULE) on ${UVICORN_HOST}:${UVICORN_PORT}"
uvicorn "$BACKEND_APP_MODULE" --host "$UVICORN_HOST" --port "$UVICORN_PORT" --reload
