from .say_hello import SayHelloCommand
from .login import LoginCommand
from .create_user import CreateUserCommand
from .refresh_token import RefreshTokenCommand
from .logout import LogoutCommand
from .me import MeCommand
from .upload_user_avatar import UploadUserAvatarCommand
from .generate_secure_download_link import GenerateSecureDownloadLinkCommand
from .add_role import AddRoleCommand
from .assign_role import AssignRoleToUserCommand
from .get_command_names import GetCommandNamesCommand
from .synch_permission import SyncPermissionCommand
from .studio.transform_template import TransformTemplateRenderCommand
from .github.register import RegisterGithubUserCommand
from .github.signin import GithubSignInCommand
from .github.start import GithubStartCommand
from .components.contents.create import CreateCompContentsWithUploadsCommand
from .components.contents.update import UpdateComponentWithUploadsCommand
from .components.contents.delete import DeleteCompContentCommand
from .components.contents.get import ContentGetCommand

from .tagging.delete import TagDeleteCommand
from .tagging.create import TagCreateCommand
from .tagging.list_active import TagListActiveCommand
